[package]
name = "hevc_parser"
version = "0.2.1"
authors = ["quietvoid"]
edition = "2018"
license = "MIT"
description = "HEVC format parser, incomplete"
repository = "https://github.com/quietvoid/hevc_parser"

[dependencies]
nom = "7.1.0"
bitvec_helpers = "0.1.1"
anyhow = "1.0.45"
