[package]
name = "hevc_parser"
version = "0.1.4"
authors = ["quietvoid"]
edition = "2018"
license = "MIT"
description = "HEVC format parser, incomplete"
repository = "https://github.com/quietvoid/hevc_parser"

[dependencies]
nom = "6.1.2"
bitvec_helpers = "0.1.0"